[package]
name = "areas"
version = "0.1.0"
authors = ["shaipe <shaipe@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# reqwest="*"
regex="*"
serde="*"
serde_json="*"
serde_derive="*"
indicatif="*"
select = "0.4.3"
hyper = "0.12.33"
pretty_env_logger = "0.3.1"
openssl = { version = "0.10", features = ["vendored"] }

[dependencies.lane_net]
path="../lane/net"
version="0.1.0"

# 可以减少编译后的文件大小
[profile.release]
lto = true

